# -*- mode: ruby; coding: utf-8; -*-
source 'https://rubygems.org'

ruby '1.9.3'

group :style do
  gem 'foodcritic', '= 3.0.3'
  gem 'rubocop', '= 0.18.1'
end

group :unit do
  gem 'chef', '= 11.10.4'
  gem 'minitest', '= 5.3.2'
  gem 'chefspec',   '= 3.4.0'
end

group :integration do
  gem 'net-ssh', '< 2.8.0'
  gem 'test-kitchen', '= 1.2.1'
  gem 'kitchen-vagrant', '= 0.14.0'
  gem 'serverspec', '= 1.1.0'
  gem 'faraday', '< 0.9'
end

group :development do
  gem 'rake', '= 10.2.2'
end
